name: Node.js CI and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: zip -r build.zip build

      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.package-version.outputs.current-version }} \
            --title "Release v${{ steps.package-version.outputs.current-version }}" \
            --notes "Release notes for version ${{ steps.package-version.outputs.current-version }}" \
            build.zip